development:
  admin_name: Fred Schoeneman 
  admin_email: fred.schoeneman@gmail.com
  admin_password: password
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: bacchan.al
  secret_key_base: 13a233d677cc6d2030c044ce93c9b340df939aae7eb2823ba3daf8f6728ad6cd9e65811009427c8a92c89f087adafc155ffbf48b703c71800bb02a5ec697bb5d

test:
  domain_name: bacchan.al 
  secret_key_base: ce72eb97bdb7133140ec66c3d1a6f3449788f70e1fa994fd9b16585d95732102fe34782c4411ed6b18da5f32ae6f8b31dd62675dd01909d5b7f35f8eb1219c25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: 1bff1a2f2b4f4299e4a8a71c95f9bebbed574e03577e0dcc46a7922f2c50e5e60a3a839135177d51f80e1a2954f77ed80a6de914e32fd4d55ea1fee67375340d
